# Generated by Django 5.0.4 on 2024-04-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_address_1_team_address_2_team_email_team_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='address_1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='address_2',
            new_name='address2',
        ),
    ]
