# Generated by Django 5.0.4 on 2024-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
