# Generated by Django 5.0.4 on 2024-04-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_modified_by'),
        ('team', '0002_alter_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='team.team'),
        ),
    ]
