# Generated by Django 5.0.4 on 2024-04-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
